let stage1 = [
    { name: "你", word: " 我是一位博士的學生", image: "img/學生.png", bEvent: 0 },
    { name: "你", word: " 我有著成為神奇寶貝大師的夢想", image: "img/學生.png", bEvent: 0 },
    { name: "你", word: " 最近我在做一項關於小火龍的報告", image: "img/學生.png", bEvent: 0 },
    { name: "你", word: " 希望透過這份研究能使我更了解小火龍", image: "img/學生.png", bEvent: 0 },
    { name: "你", word: " 要趕快把報告拿給博士看！", image: "img/學生.png", bEvent: 0 },
    { name: "你", word: " 不過博士可能會問我幾個問題，還是在那之前再看一次吧。", image: "img/學生.png", bEvent: 0 },
    { name: "地點", word: "（博士的實驗室門口）", image: "", bEvent: 0 },
    { name: "你", word: "博士！ 博士！ 博士你在嗎？", image: "img/學生.png", bEvent: 0 },
    { name: "你", word: "咦？ 博士平常這個時間不是都泡在實驗室裡做研究嗎？", image: "img/學生.png", bEvent: 0 },
    { name: "你", word: "我打個電話好了", image: "img/學生.png", bEvent: 0 },
    { name: "博士", word: "（ 鈴鈴鈴） 喂？ 請問你找誰？", image: "img/電話1.png", bEvent: 0 },
    { name: "你", word: "喂喂， 博士， 是我啦", image: "img/電話.png", bEvent: 0 },
    { name: "博士", word: "額...請問你哪位？", image: "img/電話1.png", bEvent: 0 },
    { name: "博士", word: "我是位為了給你檢查報告而來的學生。", image: "img/電話.png", bEvent: 0 },
    { name: "博士", word: "你、 你等等！ 我現在就來幫你開門。", image: "img/電話1.png", bEvent: 0 },
    { name: "博士", word: "（開門）", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "好久不見呀~", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "剛剛我做實驗做得太入迷了 ", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "所以沒聽到敲門聲，不好意思啊 ", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "你研究報告做得如何？", image: "img/博士.png", bEvent: 0 },
    { name: "你", word: "已經完成了，請您過目。", image: "img/學生.png", bEvent: 0 },
    { name: "博士", word: "讓我仔細看看。 ", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "恩，你寫得很好呢", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "但沒有記住重點的話，就沒有用了喔 ", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "那我抽問你幾個要點，看你有沒有融會貫通。", image: "img/博士.png", bEvent: 0 },
    { name: "博士", word: "小火龍是哪種神奇寶貝？", image: "img/博士.png", bEvent: 1, event: Choice_stage1_1 },
    { name: "博士", word: "小火龍的什麼部位能夠反應心情？", image: "img/博士.png", bEvent: 1, event: Choice_stage1_2 },
    { name: "博士", word: "小火龍的哪一種性別較多？", image: "img/博士.png", bEvent: 1, event: Choice_stage1_3 },
    { name: "失敗", word: "再按一下獲得成績", image: "img/失敗.png", bEvent: 1, event: Choice_stage5 },
    { name: "博士", word: "嗯…100分！！！太棒了！", image: "img/博士.png", bEvent: 0 },


]